// This file is generated by Slice Machine. Update with care!

import WhyChooseUsReason from './WhyChooseUsReason';

export {
	WhyChooseUsReason,
};

export const components = {
	why_choose_us_reason: WhyChooseUsReason,
};
